#!/usr/bin/env python3
"""Stamps out SnapStocks shell pages for deep-dive reports.

Deep-dive reports (stock-analysis/deep-dive/reports/*.html) are raw,
self-contained HTML documents generated by a separate AI/tool — each one
has its own <style> block and design tokens, so it can't be pasted into a
SnapStocks page directly without leaking styles into the site's own chrome.
Instead each report gets a thin shell page (topnav/breadcrumbs/subnav, same
as every other page) that iframes it. See DESIGN.md section 9 for the why.

Workflow: drop a new report's HTML file into
stock-analysis/deep-dive/reports/, then run this script. It stamps out a
shell for any report that doesn't have one yet (existing shells are never
overwritten unless you pass --force) and rewrites
data/deep_dive_reports.json, the manifest stock-analysis/index.html renders
its report listing from.

Usage:
    python scripts/generate_deep_dive_shells.py [--force] [--dry-run]
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REPORTS_DIR = ROOT / "stock-analysis" / "deep-dive" / "reports"
SHELL_DIR = ROOT / "stock-analysis" / "deep-dive"
MANIFEST_PATH = ROOT / "data" / "deep_dive_reports.json"

H1_RE = re.compile(r"<h1[^>]*>(.*?)</h1>", re.IGNORECASE | re.DOTALL)
TAG_RE = re.compile(r"<[^>]+>")
WS_RE = re.compile(r"\s+")

SHELL_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>{name} — Deep-Dive — SnapStocks</title>
<meta name="description" content="Narrative deep-dive report for {name}." />
<link rel="stylesheet" href="/assets/css/tokens.css" />
<link rel="stylesheet" href="/assets/css/base.css" />
<link rel="stylesheet" href="/assets/css/layout.css" />
<link rel="stylesheet" href="/assets/css/components.css" />
</head>
<body>
<div class="page-shell">

  <header class="topnav">
    <div class="container">
      <a href="/" class="brand-mark">
        <span class="logo-badge"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 17l5-6 4 4 8-10"/><path d="M15 5h6v6"/></svg></span>
        <span class="wordmark">Snap<b>Stocks</b></span>
      </a>
      <nav class="nav-primary" aria-label="Primary">
        <a href="/">Home</a>
        <a href="/macro-analysis/index.html">Macro Analysis <span class="soon-dot" title="Coming soon"></span></a>
        <a href="/sector-analysis/index.html">Sector Analysis</a>
        <a href="/stock-analysis/index.html" aria-current="page">Stock Analysis</a>
      </nav>
      <div class="nav-actions">
        <label class="nav-search">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="11" cy="11" r="7"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg>
          <input type="text" placeholder="Search ticker or sector…" autocomplete="off" />
          <kbd>/</kbd>
        </label>
        <button class="nav-toggle" data-nav-toggle aria-label="Open menu" aria-expanded="false">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><line x1="3" y1="6" x2="21" y2="6"/><line x1="3" y1="12" x2="21" y2="12"/><line x1="3" y1="18" x2="21" y2="18"/></svg>
        </button>
      </div>
    </div>
    <nav class="nav-drawer" data-nav-drawer aria-label="Mobile">
      <a href="/">Home</a>
      <a href="/macro-analysis/index.html">Macro Analysis <span class="badge-soon">Soon</span></a>
      <a href="/sector-analysis/index.html">Sector Analysis</a>
      <a href="/stock-analysis/index.html">Stock Analysis</a>
      <div class="drawer-sub">
        <a href="/stock-analysis/fundamentals/template.html">— Fundamentals</a>
        <a href="/stock-analysis/deep-dive/zaggle.html">— Deep-Dive Reports</a>
      </div>
    </nav>
  </header>

  <div class="content">
    <div class="page-header">
      <div class="container">
        <nav class="breadcrumbs"><a href="/">Home</a><span class="sep">/</span><a href="/stock-analysis/index.html">Stock Analysis</a><span class="sep">/</span><span class="current">{name} — Deep-Dive</span></nav>
        <nav class="subnav" aria-label="Stock Analysis views">
          <a href="/stock-analysis/fundamentals/template.html">Fundamentals View</a>
          <a href="{shell_url}" aria-current="page">Deep-Dive Reports</a>
        </nav>
      </div>
    </div>

    <div class="section-body container">
      <div class="report-frame-wrap">
        <div class="report-frame-loading"><span class="spinner-ring"></span>Loading report…</div>
        <iframe data-report-frame src="{report_url}" title="{name} — deep-dive report" scrolling="no"></iframe>
      </div>
    </div>
  </div>

  <footer class="site-footer">
    <div class="container">
      <div class="cols">
        <div><h5>Analysis</h5><ul><li><a href="/macro-analysis/index.html">Macro Analysis</a></li><li><a href="/sector-analysis/index.html">Sector Analysis</a></li><li><a href="/stock-analysis/index.html">Stock Analysis</a></li></ul></div>
        <div><h5>Sector Analysis</h5><ul><li><a href="/sector-analysis/momentum-chart.html">Momentum Chart</a></li><li><a href="/sector-analysis/momentum-table.html">Momentum Table</a></li><li><a href="/sector-analysis/rotation.html">Rotation Graphs</a></li></ul></div>
        <div><h5>Stock Analysis</h5><ul><li><a href="/stock-analysis/fundamentals/template.html">Fundamentals View</a></li><li><a href="/stock-analysis/deep-dive/zaggle.html">Deep-Dive Reports</a></li></ul></div>
      </div>
    </div>
  </footer>
</div>
<script src="/assets/js/nav.js"></script>
<script src="/assets/js/theme.js"></script>
<script src="/assets/js/report-frame.js"></script>
</body>
</html>
"""


def slugify(stem: str) -> str:
    slug = stem.strip().lower()
    slug = re.sub(r"[^a-z0-9]+", "-", slug)
    return slug.strip("-")


def extract_company_name(html_text: str, fallback: str) -> str:
    """Pulls the display name from the report's first <h1>.

    <h1> has been the reliable field across every report seen so far — a
    report's own <title> is not (e.g. one report's <title> says "Zaggle
    Ledger" while its <h1> says "Zaggle Prepaid Ocean Services").
    """
    match = H1_RE.search(html_text)
    if not match:
        return fallback
    name = TAG_RE.sub("", match.group(1))
    name = WS_RE.sub(" ", name).strip()
    return name or fallback


def humanize_stem(stem: str) -> str:
    words = re.split(r"[-_]+", stem.strip())
    return " ".join(w.capitalize() if w.islower() or w.isupper() else w for w in words if w)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--force", action="store_true", help="overwrite existing shell files")
    parser.add_argument("--dry-run", action="store_true", help="print what would happen, write nothing")
    args = parser.parse_args()

    if not REPORTS_DIR.exists():
        raise SystemExit(f"No reports directory at {REPORTS_DIR}")

    manifest: list[dict[str, str]] = []
    created: list[Path] = []
    skipped: list[Path] = []
    seen_slugs: dict[str, Path] = {}

    for report_path in sorted(REPORTS_DIR.glob("*.html")):
        stem = report_path.stem
        slug = slugify(stem)
        if not slug:
            print(f"warning: {report_path.name} has no usable slug, skipping")
            continue
        if slug in seen_slugs:
            print(f"warning: {report_path.name} slugifies to '{slug}', same as {seen_slugs[slug].name} - skipping")
            continue
        seen_slugs[slug] = report_path

        name = extract_company_name(report_path.read_text(encoding="utf-8"), fallback=humanize_stem(stem))
        shell_path = SHELL_DIR / f"{slug}.html"
        shell_url = f"/stock-analysis/deep-dive/{slug}.html"
        report_url = f"/stock-analysis/deep-dive/reports/{report_path.name}"

        manifest.append({"slug": slug, "name": name, "shell_url": shell_url, "report_url": report_url})

        if shell_path.exists() and not args.force:
            skipped.append(shell_path)
            continue

        if not args.dry_run:
            shell_path.write_text(
                SHELL_TEMPLATE.format(name=name, shell_url=shell_url, report_url=report_url),
                encoding="utf-8",
                newline="\n",
            )
        created.append(shell_path)

    manifest.sort(key=lambda r: r["name"])

    if not args.dry_run:
        MANIFEST_PATH.parent.mkdir(parents=True, exist_ok=True)
        MANIFEST_PATH.write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    prefix = "[dry-run] would create" if args.dry_run else "created "
    for p in created:
        print(f"{prefix} {p.relative_to(ROOT).as_posix()}")
    for p in skipped:
        print(f"skipped  {p.relative_to(ROOT).as_posix()} (already exists - use --force to overwrite)")
    manifest_note = "[dry-run] would write" if args.dry_run else "wrote   "
    print(f"{manifest_note} {MANIFEST_PATH.relative_to(ROOT).as_posix()} ({len(manifest)} reports)")


if __name__ == "__main__":
    main()
